version: '3'
services:
  composer:
    image: composer:2.5
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app
    restart: never
  phpunit:
    image: php:8.2-cli-alpine3.18
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit